# Generated by Django 3.2.3 on 2021-05-22 06:35

from django.db import migrations, models
import django.db.models.deletion
import party_register.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(default=party_register.utils.create_new_ref_number, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('isDeleted', models.CharField(default='N', max_length=1)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('counts', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('valid_to_date', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=30)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_work.admin')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party_register.party')),
            ],
        ),
        migrations.CreateModel(
            name='AdminRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_work.admin')),
            ],
        ),
    ]
