# Generated by Django 3.2.3 on 2021-06-25 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('party_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='description',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='party',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PartyRegister',
        ),
    ]
