# Generated by Django 3.2.3 on 2021-06-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_register', '0002_auto_20210625_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
